name: Push-to-EC2

on:
  push:
    branches:
      - master # Trigger deployment only on push to main branch

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Build and package Go app
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o output/server main.go

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: go-server-artifact     # Artifact name
          path: output/server          # The path to the files or directory you want to publish
          
  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with: 
          name: go-server-artifact     # Artifact name
          
      - name: Push binary file to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          SOURCE: server
          TARGET: ~/golang

      - name: Restarting server on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo chmod 700 ~/golang/server
            sudo supervisorctl restart all
